# Generated by Django 4.1.7 on 2023-03-21 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('cell', models.CharField(max_length=15)),
                ('dept', models.CharField(max_length=255)),
                ('emp_type', models.CharField(max_length=25)),
                ('postal', models.CharField(default=None, max_length=255)),
                ('ip_address', models.CharField(default=None, max_length=255)),
                ('mac_address', models.CharField(default=None, max_length=255)),
                ('reg_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
