# Generated by Django 4.1.7 on 2023-03-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='postal',
        ),
    ]
