# Generated by Django 4.1.7 on 2023-03-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_remove_employee_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='postal',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
