# Generated by Django 4.1.7 on 2023-03-25 14:56

from django.db import migrations
from django.contrib.auth.models import User

def set_superuser_flags(apps, schema_editor):
    Employee = apps.get_model('Login', 'Employee')
    try:
        superuser = Employee.objects.get(email='tech10@paicta.africa')
        superuser.is_staff = True
        superuser.is_superuser = True
        superuser.save()
    except Employee.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_employee_groups_employee_is_superuser_and_more'),
    ]

    operations = [
        migrations.RunPython(set_superuser_flags),
    ]
