# Generated by Django 4.1.7 on 2023-03-26 22:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_auto_20230325_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.CharField(default='', max_length=80)),
                ('subject', models.CharField(default='', max_length=70)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('compl_date', models.DateField(auto_now_add=True)),
                ('qual_name', models.CharField(default='', max_length=90)),
                ('grade', models.CharField(default='', max_length=78)),
                ('sec_inst', models.CharField(default='', max_length=80)),
                ('sec_subject', models.CharField(default='', max_length=70)),
                ('sec_start_date', models.DateField(auto_now_add=True)),
                ('sec_compl_date', models.DateField(auto_now_add=True)),
                ('sec_qual_name', models.CharField(default='', max_length=90)),
                ('sec_grade', models.CharField(default='', max_length=78)),
            ],
        ),
        migrations.CreateModel(
            name='EmergCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emerg_name', models.CharField(default='', max_length=57)),
                ('emerg_rel', models.CharField(default='', max_length=100)),
                ('phone_1', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_2', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('em_name', models.CharField(default='', max_length=57)),
                ('em_rel', models.CharField(default='', max_length=100)),
                ('em_phone_1', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('em_phone_2', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=90)),
                ('job_position', models.CharField(default='', max_length=90)),
                ('period_f', models.DateField(auto_now_add=True)),
                ('period_t', models.DateField(auto_now_add=True)),
                ('sec_company_name', models.CharField(default='', max_length=100)),
                ('sec_location', models.CharField(default='', max_length=90)),
                ('sec_job_position', models.CharField(default='', max_length=90)),
                ('sec_period_f', models.DateField(auto_now_add=True)),
                ('sec_period_t', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_member_name', models.CharField(default='', max_length=60)),
                ('fam_rel', models.CharField(default='', max_length=67)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('fam_member_phone', models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='PersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(default='', max_length=15)),
                ('pass_num', models.CharField(default='', max_length=20)),
                ('pass_expdate', models.DateField(auto_now_add=True)),
                ('phone_num', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=95)),
                ('marital_st', models.CharField(max_length=60)),
                ('emp_spouse', models.CharField(max_length=70)),
                ('num_child', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='resignation_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=100, null=True)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100)),
                ('noticedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resigndate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='App/static/media')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('birth_date', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(default='', max_length=150)),
                ('state', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=250)),
                ('zip_code', models.CharField(default='', max_length=90)),
                ('phone_number', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27764835831'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('department', models.CharField(default='', max_length=50)),
                ('designation', models.CharField(default='', max_length=80)),
                ('report', models.CharField(default='', max_length=95)),
            ],
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100)),
                ('terminationtype', models.CharField(max_length=100)),
                ('terminationdate', models.DateField()),
                ('reason', models.CharField(max_length=100)),
                ('noticedate', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('L', 'Leave'), ('R', 'Resignation'), ('T', 'Termination')], max_length=1)),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('deadline', models.DateField()),
                ('progress', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('sick', 'Sick'), ('vacation', 'Vacation'), ('personal', 'Personal')], max_length=20)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.employees')),
            ],
        ),
    ]
