# Generated by Django 4.1.7 on 2023-04-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_educationinfo_emergcon_employees_experienceinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_number',
            field=models.CharField(default=None, max_length=13),
        ),
    ]
