# Generated by Django 4.1.7 on 2023-04-16 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_alter_employee_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='clockin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDNumber', models.CharField(max_length=13)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('geolocation', models.CharField(max_length=255)),
                ('clockin_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('clockout_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('takebreak', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('endbreak', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
