# Generated by Django 4.1.7 on 2023-04-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_clockin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Login_employee',
        ),
    ]
