# Generated by Django 4.1.7 on 2023-04-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0015_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
